### ISSUE TITLE
Batch processing

### ISSUE THREAD

**Issue by Darel13712** [habla-liaa/encodecmae#1]
Hey! I want to use this to get embeddings for downstream tasks and everything works, but it's just too slow if I call `model.extract_features_from_file` for each file and it loads separately. What would be the easiest way to batch-process many files?

**Comment by mrpep** [comment]
Hey, I've just added a section in the colab addressing batch processing. The steps would be:
1) Create a batch of waveforms. This involves reading several files with the right sampling rate (24 kHz), padding to a common length and then stacking the arrays. This is usually done inside a torch.Dataset.
2) Call model.extract_features_from_array() with the resulting np.array or torch.Tensor. It has a signature similar to extract_features_from_file, so you can choose the desired layer and also if a np.array or a torch.Tensor is returned.
